### ISSUE TITLE
Cursor Background Color on MatchParen invisible in dark themes

### ISSUE THREAD

**Issue by jirgn** [mcchrish/zenbones.nvim#69]
Hey,
first of all - thanks a lot for the effort building this great color theme, i really like the idea and of course the looks.
I stumbled upon an issue with cursor colors when using one of the following 'dark' themes
* zenbones
* tokyobones 

If the cursor is on a parenthesis or bracket and matchparen is active, the the cursor position is barely noticeable. This in my opinion is confusing and misleeading. I would asume that the cursor background stayes the same (like in the light mode theme).

## reproducing
1. open a file with parenthesis or brackets in buffer content
2. activate matchparen (:MatchParen)
3. move cursor over bracket char

## expect
cursor is noticeable (has the same bg-color)
matching cursor is highlighted

## current
cursor is not nodiceable
matching cursor is highlighted

![Kooha-12-25-2021-22-20-22](https://user-images.githubusercontent.com/935395/147393789-7d772244-8a8d-4cb3-aba3-af19aa747a68.gif)

**Comment by mcchrish** [comment]
Do you use any matchparen plugin, like matchup etc?
Also do you have a custom `guicursor` settings?

**Comment by jirgn** [comment]
Hey thank you for the fast response.
Normally I use matchit.vim. But I reproduced the Problem when having disabled all my Plugins. And I'm not aware of any custom settings for `guicursor`.
```
# :PlugStatus
Finished. 0 error(s).
[==]

- zenbones.nvim: OK
- lush.nvim: OK

```
`:set guicursor?`
![Screenshot from 2021-12-26 11-19-13](https://user-images.githubusercontent.com/935395/147405379-93dcf5ab-2924-45e0-8621-315dfcf3852e.png)

So In my opinion no - should be all clean on my side - problem still exists

**Comment by mcchrish** [comment]
To confirm, this only happens with dark tokyonight and zenbones? Are the other dark colorschemes working fine?
Also what terminal emulator are you using?

**Comment by jirgn** [comment]
Hey, 

I use Alacritty as Terminal with a Zenbones Dark Color Set on a ArchLinux OS.
The Terminal seems to be a good call. I tried to reproduce within gTerm, and there were no problems

What I figured out when playing around with the alacritty config is, that the cursor definition in Alacritty Zenbones Dark are used.
I do not know why these terminal colors are used but when I change 
my alacritty colors to
```
  cursor:
    cursor: '#66A5AD'
    text:   '#1C1917'
    # cursor: '#1C1917'
    # text: '#C4CACF'
```
It works fine.

**Comment by mcchrish** [comment]
Do you think it's related to shipwright transformer? https://github.com/rktjmp/shipwright.nvim/issues/8

I don't use alacritty, so I'm not sure. If it fixes it, we can submit a fix.

**Comment by jirgn** [comment]
I would say yes this is related. If I get i right the color definitions are inverse here.

```yaml
cursor
     cursor: '$cursor_bg'  # changed this to bg assuming the var holds the color of the cursors surface (square)
     text: '$cursor_fg'  # changed this to fg assuming the var holds the cursor's text color
```
